/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bangcar.app.mapi.profile;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.EncodingUtils;

import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;

public class BankcardAuthVerifyReq implements org.apache.thrift.TBase<BankcardAuthVerifyReq, BankcardAuthVerifyReq._Fields>, java.io.Serializable, Cloneable, Comparable<BankcardAuthVerifyReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BankcardAuthVerifyReq");

  private static final org.apache.thrift.protocol.TField HEAD_FIELD_DESC = new org.apache.thrift.protocol.TField("head", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField AUTH_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("authId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField AMT_FEN_FIELD_DESC = new org.apache.thrift.protocol.TField("amtFen", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BankcardAuthVerifyReqStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BankcardAuthVerifyReqTupleSchemeFactory());
  }

  public com.bangcar.app.mapi.base.MApiReqHead head; // required
  /**
   * 认证流水号
   */
  public String authId; // required
  /**
   * 红包金额（单位为分）
   */
  public int amtFen; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HEAD((short)1, "head"),
    /**
     * 认证流水号
     */
    AUTH_ID((short)2, "authId"),
    /**
     * 红包金额（单位为分）
     */
    AMT_FEN((short)3, "amtFen");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HEAD
          return HEAD;
        case 2: // AUTH_ID
          return AUTH_ID;
        case 3: // AMT_FEN
          return AMT_FEN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __AMTFEN_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HEAD, new org.apache.thrift.meta_data.FieldMetaData("head", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.bangcar.app.mapi.base.MApiReqHead.class)));
    tmpMap.put(_Fields.AUTH_ID, new org.apache.thrift.meta_data.FieldMetaData("authId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AMT_FEN, new org.apache.thrift.meta_data.FieldMetaData("amtFen", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BankcardAuthVerifyReq.class, metaDataMap);
  }

  public BankcardAuthVerifyReq() {
  }

  public BankcardAuthVerifyReq(
    com.bangcar.app.mapi.base.MApiReqHead head,
    String authId,
    int amtFen)
  {
    this();
    this.head = head;
    this.authId = authId;
    this.amtFen = amtFen;
    setAmtFenIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BankcardAuthVerifyReq(BankcardAuthVerifyReq other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHead()) {
      this.head = new com.bangcar.app.mapi.base.MApiReqHead(other.head);
    }
    if (other.isSetAuthId()) {
      this.authId = other.authId;
    }
    this.amtFen = other.amtFen;
  }

  public BankcardAuthVerifyReq deepCopy() {
    return new BankcardAuthVerifyReq(this);
  }

  @Override
  public void clear() {
    this.head = null;
    this.authId = null;
    setAmtFenIsSet(false);
    this.amtFen = 0;
  }

  public com.bangcar.app.mapi.base.MApiReqHead getHead() {
    return this.head;
  }

  public BankcardAuthVerifyReq setHead(com.bangcar.app.mapi.base.MApiReqHead head) {
    this.head = head;
    return this;
  }

  public void unsetHead() {
    this.head = null;
  }

  /** Returns true if field head is set (has been assigned a value) and false otherwise */
  public boolean isSetHead() {
    return this.head != null;
  }

  public void setHeadIsSet(boolean value) {
    if (!value) {
      this.head = null;
    }
  }

  /**
   * 认证流水号
   */
  public String getAuthId() {
    return this.authId;
  }

  /**
   * 认证流水号
   */
  public BankcardAuthVerifyReq setAuthId(String authId) {
    this.authId = authId;
    return this;
  }

  public void unsetAuthId() {
    this.authId = null;
  }

  /** Returns true if field authId is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthId() {
    return this.authId != null;
  }

  public void setAuthIdIsSet(boolean value) {
    if (!value) {
      this.authId = null;
    }
  }

  /**
   * 红包金额（单位为分）
   */
  public int getAmtFen() {
    return this.amtFen;
  }

  /**
   * 红包金额（单位为分）
   */
  public BankcardAuthVerifyReq setAmtFen(int amtFen) {
    this.amtFen = amtFen;
    setAmtFenIsSet(true);
    return this;
  }

  public void unsetAmtFen() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AMTFEN_ISSET_ID);
  }

  /** Returns true if field amtFen is set (has been assigned a value) and false otherwise */
  public boolean isSetAmtFen() {
    return EncodingUtils.testBit(__isset_bitfield, __AMTFEN_ISSET_ID);
  }

  public void setAmtFenIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AMTFEN_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HEAD:
      if (value == null) {
        unsetHead();
      } else {
        setHead((com.bangcar.app.mapi.base.MApiReqHead)value);
      }
      break;

    case AUTH_ID:
      if (value == null) {
        unsetAuthId();
      } else {
        setAuthId((String)value);
      }
      break;

    case AMT_FEN:
      if (value == null) {
        unsetAmtFen();
      } else {
        setAmtFen((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HEAD:
      return getHead();

    case AUTH_ID:
      return getAuthId();

    case AMT_FEN:
      return Integer.valueOf(getAmtFen());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HEAD:
      return isSetHead();
    case AUTH_ID:
      return isSetAuthId();
    case AMT_FEN:
      return isSetAmtFen();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BankcardAuthVerifyReq)
      return this.equals((BankcardAuthVerifyReq)that);
    return false;
  }

  public boolean equals(BankcardAuthVerifyReq that) {
    if (that == null)
      return false;

    boolean this_present_head = true && this.isSetHead();
    boolean that_present_head = true && that.isSetHead();
    if (this_present_head || that_present_head) {
      if (!(this_present_head && that_present_head))
        return false;
      if (!this.head.equals(that.head))
        return false;
    }

    boolean this_present_authId = true && this.isSetAuthId();
    boolean that_present_authId = true && that.isSetAuthId();
    if (this_present_authId || that_present_authId) {
      if (!(this_present_authId && that_present_authId))
        return false;
      if (!this.authId.equals(that.authId))
        return false;
    }

    boolean this_present_amtFen = true;
    boolean that_present_amtFen = true;
    if (this_present_amtFen || that_present_amtFen) {
      if (!(this_present_amtFen && that_present_amtFen))
        return false;
      if (this.amtFen != that.amtFen)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(BankcardAuthVerifyReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHead()).compareTo(other.isSetHead());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHead()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.head, other.head);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAuthId()).compareTo(other.isSetAuthId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authId, other.authId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAmtFen()).compareTo(other.isSetAmtFen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAmtFen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.amtFen, other.amtFen);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BankcardAuthVerifyReq(");
    boolean first = true;

    sb.append("head:");
    if (this.head == null) {
      sb.append("null");
    } else {
      sb.append(this.head);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("authId:");
    if (this.authId == null) {
      sb.append("null");
    } else {
      sb.append(this.authId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("amtFen:");
    sb.append(this.amtFen);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (head != null) {
      head.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BankcardAuthVerifyReqStandardSchemeFactory implements SchemeFactory {
    public BankcardAuthVerifyReqStandardScheme getScheme() {
      return new BankcardAuthVerifyReqStandardScheme();
    }
  }

  private static class BankcardAuthVerifyReqStandardScheme extends StandardScheme<BankcardAuthVerifyReq> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BankcardAuthVerifyReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HEAD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.head = new com.bangcar.app.mapi.base.MApiReqHead();
              struct.head.read(iprot);
              struct.setHeadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AUTH_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.authId = iprot.readString();
              struct.setAuthIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // AMT_FEN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.amtFen = iprot.readI32();
              struct.setAmtFenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BankcardAuthVerifyReq struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.head != null) {
        oprot.writeFieldBegin(HEAD_FIELD_DESC);
        struct.head.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.authId != null) {
        oprot.writeFieldBegin(AUTH_ID_FIELD_DESC);
        oprot.writeString(struct.authId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(AMT_FEN_FIELD_DESC);
      oprot.writeI32(struct.amtFen);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BankcardAuthVerifyReqTupleSchemeFactory implements SchemeFactory {
    public BankcardAuthVerifyReqTupleScheme getScheme() {
      return new BankcardAuthVerifyReqTupleScheme();
    }
  }

  private static class BankcardAuthVerifyReqTupleScheme extends TupleScheme<BankcardAuthVerifyReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BankcardAuthVerifyReq struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetHead()) {
        optionals.set(0);
      }
      if (struct.isSetAuthId()) {
        optionals.set(1);
      }
      if (struct.isSetAmtFen()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetHead()) {
        struct.head.write(oprot);
      }
      if (struct.isSetAuthId()) {
        oprot.writeString(struct.authId);
      }
      if (struct.isSetAmtFen()) {
        oprot.writeI32(struct.amtFen);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BankcardAuthVerifyReq struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.head = new com.bangcar.app.mapi.base.MApiReqHead();
        struct.head.read(iprot);
        struct.setHeadIsSet(true);
      }
      if (incoming.get(1)) {
        struct.authId = iprot.readString();
        struct.setAuthIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.amtFen = iprot.readI32();
        struct.setAmtFenIsSet(true);
      }
    }
  }

}

